[project]
name = "lib-c"
version = "0.0.0"
description = ""
requires-python = ">=3.7"
readme = "README.md"
dependencies = []

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
